//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Hutech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Event
    {
        public int Id_CE { get; set; }
        public string Name_CE { get; set; }
        public Nullable<int> Id_Khoa { get; set; }
    
        public virtual Khoa Khoa { get; set; }
    }
}
