//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Hutech.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EVENTEntities : DbContext
    {
        public EVENTEntities()
            : base("name=EVENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Cate_News> Cate_News { get; set; }
        public virtual DbSet<Category_Event> Category_Event { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<linkAddress> linkAddresses { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<MXH> MXHs { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<RoleDetail> RoleDetails { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<SV_SK> SV_SK { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThongTinWebsite> ThongTinWebsites { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<VoteLog> VoteLogs { get; set; }
    }
}
