//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Hutech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDetail
    {
        public int Id_Role { get; set; }
        public int Id_Admin { get; set; }
        public int Id { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Role Role { get; set; }
    }
}
