//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Hutech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV_SK
    {
        public Nullable<int> ID_SV { get; set; }
        public Nullable<int> ID_Events { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Checkin { get; set; }
        public int ID_Detail_Event_Student { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
